int _stdcall cTpCintelnew();
int _stdcall cTintelnew();
int _stdcall cCintelnew();
void _stdcall vxm_x1_x87_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x1_x87_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x1_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x1_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x1_avx_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x1_avx_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x2_x87_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x2_x87_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x2_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x2_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x2_avx_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x2_avx_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x4_x87_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x4_x87_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x4_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x4_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x4_avx_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x4_avx_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x8_x87_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x8_x87_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x8_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x8_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x6_x87_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x6_x87_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x3_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x3_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x6_sse_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x6_sse_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x3_avx_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x3_avx_dp(double *a, double *b, double *c, int d, int e);
void _stdcall vxm_x6_avx_sp(float *a, float *b, float *c, int d, int e);
void _stdcall vxm_x6_avx_dp(double *a, double *b, double *c, int d, int e);
