function [methodinfo,structs,enuminfo,ThunkLibName]=tictoc_mx
%TICTOC_MX Create structures to define interfaces found in 'tictoc'.

%This function was generated by loadlibrary.m parser version 1.1.6.35 on Mon Mar 25 19:15:18 2019
%perl options:'tictoc.i -outfile=tictoc_mx.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% int _stdcall M_toc ( long * a ); 
fcns.name{fcnNum}='M_toc'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'longPtr'};fcnNum=fcnNum+1;
% double _stdcall M_rtoc ( long * a ); 
fcns.name{fcnNum}='M_rtoc'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='double'; fcns.RHS{fcnNum}={'longPtr'};fcnNum=fcnNum+1;
% void _stdcall M_tic ( long * a ); 
fcns.name{fcnNum}='M_tic'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'longPtr'};fcnNum=fcnNum+1;
methodinfo=fcns;