function [methodinfo,structs,enuminfo,ThunkLibName]=blend_mx
%BLEND_MX Create structures to define interfaces found in 'blend'.

%This function was generated by loadlibrary.m parser version 1.1.6.35 on Tue Apr  2 11:42:28 2019
%perl options:'blend.i -outfile=blend_mx.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% int _stdcall MMXsupport (); 
fcns.name{fcnNum}='MMXsupport'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% void _stdcall blend ( uint * a , uint * b , uint * c ); 
fcns.name{fcnNum}='blend'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'voidPtr', 'voidPtr', 'voidPtr'};fcnNum=fcnNum+1;
methodinfo=fcns;